-- INSERTING SINGLE DATA INTO EXISTING TABLE --

-- iNSERTING INTO A SINGLE ROW --

USE sql_store;

SELECT *
FROM customers;

INSERT INTO customers 
VALUES (DEFAULT,'JOHN','Smith','1990-01-01',NULL,'address','city','CA',DEFAULT);